version: "3.3"
services:
 # Lunnem Api
  api_nginx:
    image: nginx:alpine
    container_name: nginx-api
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "92:80"
    networks:
      - chama_network
  backend:
    build: .
    container_name: chama-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 9000
    networks:
      - chama_network
  front:
    image: nginx:alpine
    container_name: nginx-front
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./front_workshop:/var/www/html/
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "91:80"
    networks:
      - chama_network
networks:
  chama_network:
    driver: bridge